modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/UniversalExporters/UniversalExporter/isssues"
license = "AGPLv3"

[[mods]]
modId = "uni_exporter"
version = "${version}"
displayName = "UniversalExporter"
displayURL = "https://github.com/UniversalExporters/UniversalExporter"
authors = "UniversalExporters"
description = '''
Universal multi-modloader exporter for mcmod.cn
'''
logoFile = "icon.png"

[[dependencies.uni_exporter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1]"
ordering = "NONE"
side = "BOTH"