modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "AGPLv3"

[[mods]]
modId = "uni_exporter"
version = "${version}"
displayName = "UniversalExporter"
authors = "UniversalExporters"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "icon.png"

[[dependencies.uni_exporter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.uni_exporter]]
modId = "architectury"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"