{
  "formatVersion": "1.1",
  "component": {
    "group": "org.uniexporter.exporter",
    "module": "UniversalExporter-adaptor",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UniversalExporter-adaptor-0.1.0.jar",
          "url": "UniversalExporter-adaptor-0.1.0.jar",
          "size": 17732,
          "sha512": "344db70ae032c1e53526b41db29df888ab123b322a352039f3766bd41fff732fef004e537ec41e9698f12977259e0cf3faf615bbdbe5959d36f072a484547fcf",
          "sha256": "701e14a1f4d2f9350dd91d7a1cd4e3768dd2b6eef4b9df126118aa84c62e3a20",
          "sha1": "f4bdbe6a64b7269b6a4cba7e8fd1970ee849314d",
          "md5": "9fe2f6d9fb9918e46f79fb198d26ff15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "UniversalExporter-adaptor-0.1.0.jar",
          "url": "UniversalExporter-adaptor-0.1.0.jar",
          "size": 17732,
          "sha512": "344db70ae032c1e53526b41db29df888ab123b322a352039f3766bd41fff732fef004e537ec41e9698f12977259e0cf3faf615bbdbe5959d36f072a484547fcf",
          "sha256": "701e14a1f4d2f9350dd91d7a1cd4e3768dd2b6eef4b9df126118aa84c62e3a20",
          "sha1": "f4bdbe6a64b7269b6a4cba7e8fd1970ee849314d",
          "md5": "9fe2f6d9fb9918e46f79fb198d26ff15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "UniversalExporter-adaptor-0.1.0-sources.jar",
          "url": "UniversalExporter-adaptor-0.1.0-sources.jar",
          "size": 11507,
          "sha512": "a0d6e2267ec5d68c49a37285123b32e89ab08a9d56362d96624b77af6888a327ef341a343042413358851d1faf74bad460508b752489ce5f3f68baff415b1c45",
          "sha256": "8d6c384bcea162baf01bbfa2edb3e2ba4185db4e025efb01bb2f6210f2fe7d44",
          "sha1": "b20f9ae09708cd90efbe17d099721c2648ce1690",
          "md5": "42a160a6cee98551a2dc92582b02450d"
        }
      ]
    }
  ]
}
