{
  "formatVersion": "1.1",
  "component": {
    "group": "org.uniexporter.exporter",
    "module": "UniversalExporter-adaptor",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UniversalExporter-adaptor-0.1.0.jar",
          "url": "UniversalExporter-adaptor-0.1.0.jar",
          "size": 17750,
          "sha512": "08dc9f38b882a7dd159ec7064db1d06afa4d02341b5e4756672843180c62fc23a32d530933a3bb7e76f97f28eee1d0a6a4da322a0565f330e2e654928bf7897e",
          "sha256": "e51136825280492dcce806def9228f3ac1ce655ef55c9b6c529df9a306c2edd7",
          "sha1": "6d179a708f4175b88c73f272c3bbec8b8ef05a84",
          "md5": "0557311d541b4b8881045c917a92f073"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "UniversalExporter-adaptor-0.1.0.jar",
          "url": "UniversalExporter-adaptor-0.1.0.jar",
          "size": 17750,
          "sha512": "08dc9f38b882a7dd159ec7064db1d06afa4d02341b5e4756672843180c62fc23a32d530933a3bb7e76f97f28eee1d0a6a4da322a0565f330e2e654928bf7897e",
          "sha256": "e51136825280492dcce806def9228f3ac1ce655ef55c9b6c529df9a306c2edd7",
          "sha1": "6d179a708f4175b88c73f272c3bbec8b8ef05a84",
          "md5": "0557311d541b4b8881045c917a92f073"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "UniversalExporter-adaptor-0.1.0-sources.jar",
          "url": "UniversalExporter-adaptor-0.1.0-sources.jar",
          "size": 11521,
          "sha512": "12f24393a218a134e798bbc22dd16aa4908c7c9c1d27e4f877ffcc089c167ba39087102be7cb39f322dc1c714fb00671e7688aa6dc4f6408104adcfdac288621",
          "sha256": "805a6598b1586bd5085340578de7e38801f0b8de49956a1498c1e3f94277128e",
          "sha1": "9627e4bffe61ee517e52e60642a553d0728c1294",
          "md5": "3005cb839979080287baa0626a70d7da"
        }
      ]
    }
  ]
}
